<template>
  <div class="w-full min-h-screen bg-white font-montserrat flex flex-col items-center justify-center p-6">
    <div class="w-full max-w-[380px] rounded-3xl p-8 text-center text-white" :style="cardStyle">
      <h1 class="text-lg font-semibold mb-4">
        Your Secure Password Has Been Generated
      </h1>
      <p class="text-sm leading-5 mb-6">
        For your security, a strong password was automatically generated by our system using industry-standard protection methods.<br>
        <b>We do not store or have access to your password.</b> Please copy and save it securely — you will need it to log in to DBD Capital via browser.<br>
        You can change this password later in your account settings.
      </p>
      <div class="flex flex-col items-center gap-3 mb-6">
        <div class="w-full flex items-center justify-center bg-white/20 rounded-lg px-4 py-2">
          <span class="font-mono text-base select-all">{{ password }}</span>
          <button @click="copyPassword" class="ml-3 px-3 py-1 rounded bg-dbd-orange text-white font-semibold hover:opacity-90 active:scale-[0.97] transition">
            {{ copied ? 'Скопировано!' : 'Копировать' }}
          </button>
        </div>
      </div>
      <button @click="goFavorites" class="w-full h-12 rounded-full bg-gradient-to-r from-dbd-primary to-[#473FFF] font-bold text-white hover:opacity-90 active:scale-[0.97] transition">
        Continue
      </button>
    </div>
  </div>
</template>
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
const router = useRouter()
const cardStyle = { background: 'linear-gradient(90deg, #2019CE 20.91%, #473FFF 68.93%)' }
const password = ref('')
const copied = ref(false)
onMounted(() => {
  password.value = sessionStorage.getItem('generatedPassword') || ''
  sessionStorage.removeItem('generatedPassword')
})
const copyPassword = async () => {
  try {
    await navigator.clipboard.writeText(password.value)
    copied.value = true
    setTimeout(() => copied.value = false, 1500)
  } catch {}
}
const goFavorites = () => router.replace('/favorites')
</script>
<style scoped>
* { will-change:auto }
</style>
