<template>
  <div class="w-full min-h-screen bg-white font-montserrat flex flex-col items-center justify-center p-6">
    <div class="w-full max-w-[380px] rounded-3xl p-8 text-center text-white" :style="cardStyle">
      <h1 class="text-lg font-semibold mb-4">
        Your Secure Password Has Been Generated
      </h1>
      <p class="text-sm leading-5 mb-6">
        For your security, a strong password was automatically generated by our system using industry-standard protection methods.<br>
        <b>We do not store or have access to your password.</b> Please copy and save it securely — you will need it to log in to DBD Capital via browser.<br>
        You can change this password later in your account settings.
      </p>
      <!-- Копирование пароля в стиле WebReferralLink -->
      <div class="relative w-full max-w-sm h-13 sm:h-14 md:h-16 rounded-full border border-blue-600 border-opacity-60 bg-white bg-opacity-10 flex items-center transition-all duration-400 ease-out overflow-hidden mb-6"
        :class="{ 'link-copied-state': copied }">
        <!-- Пароль -->
        <div v-if="!copied" class="flex-1 px-4 sm:px-6 py-3.5 overflow-hidden flex items-center justify-start">
          <span class="password-text block font-mono select-all w-full text-left">
            {{ password }}
          </span>
        </div>
        <!-- Copied State -->
        <div v-if="copied" class="flex-1 px-4 sm:px-6 py-3.5 overflow-hidden flex items-center justify-start">
          <div class="link-copied-content flex items-center gap-2">
            <span class="link-copied-text text-white font-bold">Copied</span>
            <div class="link-copied-icon">
              <svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="14" cy="14" r="14" fill="white"/>
              </svg>
              <svg class="link-tick-svg" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M11.3242 0.926106C10.7978 0.642629 10.2106 1.18934 9.86633 1.51331C9.07667 2.28275 8.40848 3.17368 7.65925 3.98362C6.82907 4.87455 6.05963 5.76548 5.20919 6.6362C4.72323 7.12216 4.19677 7.64862 3.8728 8.25607C3.14385 7.54734 2.51615 6.7779 1.70621 6.15023C1.11901 5.70477 0.147086 5.38079 0.167334 6.45396C0.207831 7.85113 1.44299 9.34952 2.35416 10.3012C2.73888 10.7061 3.24509 11.1313 3.8323 11.1516C4.54099 11.1921 5.26994 10.3417 5.69515 9.87594C6.44438 9.06601 7.05183 8.15479 7.74024 7.32464C8.63118 6.23123 9.54236 5.15803 10.413 4.04436C10.9597 3.35592 12.6809 1.65502 11.3242 0.926106ZM1.05823 6.37297C1.03798 6.37297 1.01773 6.37297 0.977238 6.39318C0.896244 6.37297 0.835499 6.35268 0.754505 6.31219C0.815251 6.27169 0.916493 6.29194 1.05823 6.37297Z" fill="#07B80E"/>
              </svg>
            </div>
          </div>
        </div>
        <!-- Copy Button -->
        <button
          v-if="!copied"
          class="absolute right-0 top-0 bottom-0 flex items-center justify-center px-4 sm:px-5 md:px-6 bg-dbd-off-white border-l border-indigo-700 rounded-r-full cursor-pointer transition-all duration-300 ease-out hover:bg-blue-50 hover:-translate-y-0.5 hover:scale-105 active:translate-y-0 active:scale-95"
          @click="copyPassword"
        >
          <svg class="w-5 h-5 sm:w-6 sm:h-6 md:w-7 md:h-7 text-indigo-700" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M18.0655 0.5H7.60611C6.97596 0.5 6.37161 0.727045 5.92603 1.13119C5.48044 1.53533 5.23011 2.08346 5.23011 2.65501V3.48385H4.04211C3.38111 3.48385 2.74718 3.72201 2.27978 4.14594C1.81239 4.56986 1.5498 5.14483 1.5498 5.74435V19.2395C1.5498 19.839 1.81239 20.414 2.27978 20.8379C2.74718 21.2618 3.38111 21.5 4.04211 21.5H14.2772C14.9382 21.5 15.5721 21.2618 16.0395 20.8379C16.5069 20.414 16.7695 19.839 16.7695 19.2395V18.486H18.0655C18.6907 18.4861 19.291 18.2634 19.7369 17.866C20.1829 17.4685 20.4389 16.9281 20.4498 16.3611V2.65501C20.4476 2.08277 20.1954 1.53465 19.7485 1.13073C19.3016 0.7268 18.6964 0.499997 18.0655 0.5ZM15.108 19.2395C15.108 19.4393 15.0204 19.631 14.8646 19.7723C14.7088 19.9136 14.4975 19.993 14.2772 19.993H4.04211C3.82178 19.993 3.61047 19.9136 3.45467 19.7723C3.29887 19.631 3.21134 19.4393 3.21134 19.2395V5.74435C3.21134 5.54451 3.29887 5.35285 3.45467 5.21154C3.61047 5.07024 3.82178 4.99085 4.04211 4.99085H14.2772C14.4975 4.99085 14.7088 5.07024 14.8646 5.21154C15.0204 5.35285 15.108 5.54451 15.108 5.74435V19.2395ZM18.7883 16.3611C18.7861 16.5337 18.709 16.6985 18.5737 16.8198C18.4383 16.9411 18.2558 17.0092 18.0655 17.0092H16.7695V5.74435C16.7695 5.14483 16.5069 4.56986 16.0395 4.14594C15.5721 3.72201 14.9382 3.48385 14.2772 3.48385H6.89165V2.65501C6.89165 2.48314 6.96693 2.31832 7.10091 2.19679C7.2349 2.07527 7.41663 2.007 7.60611 2.007H18.0655C18.16 2.006 18.2538 2.02203 18.3415 2.05414C18.4291 2.08626 18.5089 2.13384 18.5761 2.19411C18.6433 2.25438 18.6967 2.32616 18.7331 2.40527C18.7695 2.48439 18.7883 2.56927 18.7883 2.65501V16.3611Z" fill="#2019CE"/>
          </svg>
        </button>
      </div>
      <button @click="goFavorites" class="continue-button w-full h-12 rounded-full bg-gradient-to-r from-dbd-primary to-[#473FFF] font-bold text-white hover:opacity-90 active:scale-[0.97] transition">
        Continue
      </button>
    </div>
  </div>
</template>
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
const router = useRouter()
const cardStyle = { background: 'linear-gradient(90deg, #2019CE 20.91%, #473FFF 68.93%)' }
const password = ref('')
const copied = ref(false)
onMounted(() => {
  password.value = sessionStorage.getItem('generatedPassword') || ''
  sessionStorage.removeItem('generatedPassword')
})
const copyPassword = async () => {
  try {
    await navigator.clipboard.writeText(password.value)
    copied.value = true
    setTimeout(() => copied.value = false, 1500)
  } catch {}
}
const goFavorites = () => router.replace('/favorites')
</script>

<style scoped>
* { will-change:auto }
/* Стили для блока копирования пароля, взяты из HoldersView.vue */
.link-copied-state {
  border: 1px solid #07B80E !important;
  background: #129E0F !important;
  transform: scale(1.02) !important;
}

.password-text {
  font-size: 1.15rem;
  font-weight: 600;
  color: #fff;
  letter-spacing: 0.04em;
  text-align: left;
  line-height: 1.8rem;
  background: none;
  width: 100%;
  user-select: all;
  text-shadow: 0 1px 6px rgba(32,25,206,0.12);
  white-space: nowrap;
  overflow-x: auto;
  text-overflow: ellipsis;
}

.link-copied-content {
  display: flex;
  align-items: center;
  gap: 8px;
  animation: fadeInScale 0.4s cubic-bezier(0.4, 0, 0.2, 1);
}

.continue-button {
  border: 2px solid #FFFFFF !important;
  transform: scale(1);
  will-change: transform, border-color, color, background-color;
}

.link-copied-text {
  color: #FFF;
  font-family: Montserrat, -apple-system, Roboto, Helvetica, sans-serif;
  font-size: 14px;
  font-weight: 600;
  line-height: 22px;
  text-align: center;
  animation: slideInLeft 0.3s ease-out 0.1s both;
}

.link-copied-icon {
  position: relative;
  width: 28px;
  height: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  animation: bounceIn 0.5s ease-out 0.2s both;
}

.link-tick-svg {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

@keyframes fadeInScale {
  0% {
    opacity: 0;
    transform: scale(0.9);
  }
  50% {
    opacity: 0.8;
    transform: scale(1.05);
  }
  100% {
    opacity: 1;
    transform: scale(1);
  }
}

@keyframes slideInLeft {
  from {
    opacity: 0;
    transform: translateX(-10px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes bounceIn {
  0% {
    opacity: 0;
    transform: scale(0.3) rotate(-10deg);
  }
  50% {
    opacity: 0.9;
    transform: scale(1.1) rotate(5deg);
  }
  80% {
    transform: scale(0.95) rotate(-2deg);
  }
  100% {
    opacity: 1;
    transform: scale(1) rotate(0deg);
  }
}
</style>
